version: "3.9"
volumes:
  bd: {}
services:
  web:
    image: gaonis/iviaje:base
    container_name: iviaje
    volumes:
      - ./code:/code
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: Kojaca009#
      MYSQL_DATABASE: iviaje
      MYSQL_USER: db_user1
      MYSQL_PASSWORD: pass
    ports:
      - 23306:3306
    volumes:
      - ./bd/test.sql:/docker-entrypoint-initdb.d/test.sql
